export const mock = `<h1>Est tenetur odio cum accusamus esse ut fugiat sapiente. </h1><p>Lorem ipsum dolor sit amet. Eos repellendus rerum <em>Non ratione eum optio molestias a error fuga</em> aut dolore rerum et natus nesciunt. Cum velit veniam ut error temporibus <strong>Qui debitis ea aliquam dolorem aut libero labore ea adipisci provident</strong>. Vel dolorem providentAb aliquam aut asperiores velit et vero exercitationem et exercitationem libero! </p><pre><code>def calcular_media(lista):
total = sum(lista)
media = total / len(lista)
return media

notas = [85, 90, 78, 92, 88]
media_notas = calcular_media(notas)
print(f'A média das notas é: {media_notas}')
</code></pre><h2>Aut magnam eaque et tempora nemo At facere reprehenderit. </h2><p>Non ducimus voluptatibus <strong>Et galisum</strong> qui ipsum voluptates ea eius sapiente? Sed quis excepturi et dolorum quia <a href="https://www.loremipzum.com" target="_blank">In distinctio hic culpa reprehenderit aut excepturi quia 33 assumenda dignissimos</a>. Qui molestiae molestias <em>Eum nihil sed galisum saepe nam voluptates nulla rem recusandae reiciendis</em> ut soluta saepe qui dolores alias! Et dolor sunt rem nobis exercitationemNam placeat et minima voluptas est dolores nihil et odio molestias. </p><ul><li>Hic nobis molestiae non magni nesciunt qui dolores magnam et nemo voluptas? </li><li>Non perferendis sint ea cupiditate quibusdam aut placeat quaerat ex veritatis quia. </li><li>A officia ipsa ex culpa nesciunt sit consectetur harum. </li><li>At blanditiis consequatur aut quasi consequatur? </li><li>Est corporis magnam est quisquam fuga qui voluptas alias sed fuga itaque? </li></ul><h3>33 accusamus labore ut cupiditate atque aut quisquam dolorem. </h3><p>Sed eveniet culpaAb accusantium ut corporis illum non pariatur natus eum architecto dolorem ea magni incidunt. Nam labore porro <em>Eum sint</em> et quod voluptatem 33 ullam sequi! Est blanditiis illoEt consequatur id accusantium placeat a facilis omnis ex fugiat voluptate est blanditiis autem ut blanditiis nesciunt. Rem reprehenderit amet in modi facilisin assumenda est quasi laborum aut quod officia. </p><dl><dt><dfn>A libero quos sit praesentium enim. </dfn></dt><dd>Et totam quisquam et rerum praesentium. </dd><dt><dfn>Ea nihil repellat qui placeat pariatur. </dfn></dt><dd>Aut dolor maiores ad laboriosam rerum quo Quis voluptates ad consequatur tenetur. </dd></dl><blockquote cite="https://www.loremipzum.com">Aut laudantium quisquam aut molestias galisum ab iusto vitae sit explicabo omnis ut atque corporis vel excepturi itaque. </blockquote>
<img src="http://placeholder.com/1024"/>`;
